# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_nnmf <- function(A, k, max_iter, rel_tol, n_threads, verbose, inner_max_iter, inner_rel_tol, trace) {
    .Call(`_scNMF_c_nnmf`, A, k, max_iter, rel_tol, n_threads, verbose, inner_max_iter, inner_rel_tol, trace)
}

c_project <- function(A, W, n_threads, inner_max_iter, inner_rel_tol) {
    .Call(`_scNMF_c_project`, A, W, n_threads, inner_max_iter, inner_rel_tol)
}